export const accesos:object = {
    ROOT: [
      'POST-/usuario',
      'GET-/usuario',
      'GET-/bodega',
      'POST-/bodega',
      'PUT-/bodega',
      'GET-/proveedor/tipo-proveedores/all',
      'POST-/proveedor',
      'GET-/proveedor',
      'PUT-/proveedor',
      'GET-/bodega/activa',
      'GET-/unidad-medida',
      'POST-/insumo',
      'GET-/insumo',
      'PUT-/insumo'
    ],
    ADMIN:[
      'POST-/usuario',
      'GET-/usuario',
      'GET-/bodega',
      'POST-/bodega',
      'PUT-/bodega',
      'GET-/proveedor/tipo-proveedores/all',
      'POST-/proveedor',
      'GET-/proveedor',
      'PUT-/proveedor',
      'GET-/bodega/activa',
      'GET-/unidad-medida',
      'POST-/insumo',
      'GET-/insumo',
      'PUT-/insumo'
    ],
    cliente:[
      'GET-/usuario'
    ]
  }